In [6]:
# 체류시간 예측 실험
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
BASE_PATH = os.getcwd()
DATA_PATH = BASE_PATH + r'\online_shoppers_intention.csv'

df = pd.read_csv(DATA_PATH, encoding='utf-8')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12330 entries, 0 to 12329
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Administrative           12330 non-null  int64
 1   Administrative_Duration  12330 non-null  float64
 2   Informational            12330 non-null  int64
 3   Informational_Duration   12330 non-null  float64
 4   ProductRelated           12330 non-null  int64
 5   ProductRelated_Duration  12330 non-null  float64
 6   BounceRates              12330 non-null  float64
 7   ExitRates                12330 non-null  float64
 8   PageValues               12330 non-null  float64
 9   SpecialDay               12330 non-null  float64
 10  Month                    12330 non-null  object
 11  OperatingSystems         12330 non-null  int64
 12  Browser                  12330 non-null  int64
 13  Region                   12330 non-null  int64
 14  TrafficType              12330 non-null  int64
 15  VisitorType              12330 non-null  object
 16  Weekend                  12330 non-null  bool
 17  Revenue                  12330 non-null  bool
dtypes: bool(2), float64(7), int64(7), object(2)
memory usage: 1.5+ MB

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [ ]:
def preprocess_data(df):
    df_preprocessed = df.copy()

    # 새로운 특성 생성
    df_preprocessed['Total_Duration'] = (
        df_preprocessed['Administrative_Duration'] + 
        df_preprocessed['Informational_Duration'] + 
        df_preprocessed['ProductRelated_Duration']
    )
    df_preprocessed['Total_Pages'] = (
        df_preprocessed['Administrative'] + 
        df_preprocessed['Informational'] + 
        df_preprocessed['ProductRelated']
    )
    df_preprocessed['Engagement_Rate'] = (
        df_preprocessed['PageValues'] / (
            df_preprocessed['BounceRates'] + 
            df_preprocessed['ExitRates'] + 1e-8
        )
    )

    # 범주형 변수 인코딩
    from sklearn.preprocessing import LabelEncoder

    le_month = LabelEncoder()
    le_visitor = LabelEncoder()
    
    df_preprocessed['Month_Encoded'] = le_month.fit_transform(df_preprocessed['Month'])
    df_preprocessed['VisitorType_Encoded'] = le_visitor.fit_transform(df_preprocessed['VisitorType'])
    df_preprocessed['Weekend_Encoded'] = df_preprocessed.fit_transform(df_preprocessed['Weekend']).astype(int)

    return df_preprocessed


# 데이터 전처리
df_preprocessed = preprocess_data(df)
print("전처리 완료")
print(f"새로운 특성 추가: Total_Duration, Total_Pages, Engagement_Rate")
print(f"범주형 변수 인코딩: Month, VisitorType, Weekend\n")

AttributeError: 'DataFrame' object has no attribute 'fit_transform'